[[main]]
    name = "ALL"
    pageRef = "/posts"
    weight = 10

[[main]]
    name = "カテゴリ"
    pageRef = "/categories"
    weight = 15

[[main]]
    name = "技術解説"
    parent = "カテゴリ"
    pageRef = "/categories/技術解説"
    weight = 10

[[main]]
    name = "やってみた"
    parent = "カテゴリ"
    pageRef = "/categories/やってみた"
    weight = 20

[[main]]
    name = "ポエム"
    parent = "カテゴリ"
    pageRef = "/categories/ポエム"
    weight = 20

[[main]]
    name = "タグ"
    pageRef = "/tags"
    weight = 20

[[main]]
    name = "C言語"
    parent = "タグ"
    pageRef = "/tags/C言語"
    weight = 5

[[main]]
    name = "C++"
    parent = "タグ"
    pageRef = "/tags/c++"
    weight = 10

[[main]]
    name = "Rust"
    parent = "タグ"
    pageRef = "/tags/rust"
    weight = 15

[[main]]
    name = "将棋"
    pageRef = "/tags/将棋"
    parent = "タグ"
    weight = 105

[[main]]
    name = "KmoringHeights"
    pageRef = "/tags/KomoringHeights"
    parent = "タグ"
    weight = 110

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/komori-n/blog"
  weight = 100
