[[main]]
    name = "ALL"
    pageRef = "/posts"
    weight = 10

[[main]]
    name = "カテゴリ"
    pageRef = "/categories"
    weight = 15

[[main]]
    name = "タグ"
    pageRef = "/tags"
    weight = 20

[[main]]
    name = "C/C++"
    parent = "タグ"
    pageRef = "/tags/c/c++"
    weight = 10

[[main]]
    name = "Rust"
    parent = "タグ"
    pageRef = "/tags/rust"
    weight = 10

[[main]]
    name = "詰将棋エンジン"
    pageRef = "/tags/詰将棋"
    parent = "タグ"
    weight = 10

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/komori-n/blog"
  weight = 100
