[[main]]
    name = "ALL"
    pageRef = "/posts"
    weight = 10

[[main]]
    name = "Category"
    pageRef = "/categories"
    weight = 15

[[main]]
    name = "Tag"
    pageRef = "/tags"
    weight = 20
